apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: floormat
  name: floormat
spec:
  ports:
    - name: "1339"
      port: 1339
      targetPort: 1339
  selector:
    io.kompose.service: floormat
