ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-ratelimit@kubernetescrd
  hosts:
    - host: nginx.wgmy
      paths:
        - path: /
          pathType: Prefix

volumes:
  - name: conf
    configMap:
      name: '{{ include "nginx.fullname" . }}'

volumeMounts:
  - name: conf
    mountPath: /etc/nginx/conf.d
    readOnly: true

configMap:
  enabled: true
  data:
    default.conf: |
      set_real_ip_from  10.42.0.0/16;
      real_ip_header    X-Real-IP;

      server {
        listen       80 reuseport;
        server_name  _;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location /vault/ui/ {
          deny   all;
        }

        location /vault/ {
          allow  10.0.0.0/8;
          allow  172.16.0.0/12;
          allow  192.168.0.0/16;
          deny   all;

          proxy_pass  http://vault.vault:8200/;
        }
      }
