apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rigged2
  name: rigged2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rigged2
  template:
    metadata:
      labels:
        io.kompose.service: rigged2
    spec:
      containers:
        - image: rigged2
          name: rigged2
          ports:
            - containerPort: 1337
              hostPort: 1337
              protocol: TCP
      restartPolicy: Always
