apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rigged2
  name: rigged2
spec:
  ports:
    - name: "1337"
      port: 1337
      targetPort: 1337
  selector:
    io.kompose.service: rigged2
